# Generated by Django 3.2.20 on 2023-08-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='id_inv_pr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
