# Generated by Django 3.2.20 on 2023-08-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_id_inv_pr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialproject2023',
            name='own_revenue',
        ),
        migrations.RemoveField(
            model_name='financialproject2023',
            name='own_revenue_currency',
        ),
        migrations.RemoveField(
            model_name='financialproject2023',
            name='vol_invest',
        ),
        migrations.RemoveField(
            model_name='financialproject2023',
            name='vol_invest_currency',
        ),
    ]
