# Generated by Django 3.2.20 on 2023-08-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20230824_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialprojectgov2023',
            old_name='fact_consider',
            new_name='fact_consider_gov',
        ),
        migrations.RenameField(
            model_name='financialprojectgov2023',
            old_name='fact_consider_currency',
            new_name='fact_consider_gov_currency',
        ),
        migrations.RenameField(
            model_name='financialprojectgov2023',
            old_name='fact_work',
            new_name='fact_work_gov',
        ),
        migrations.RenameField(
            model_name='financialprojectgov2023',
            old_name='fact_work_currency',
            new_name='fact_work_gov_currency',
        ),
        migrations.RenameField(
            model_name='financialprojectgov2023',
            old_name='plan_consider',
            new_name='plan_consider_gov',
        ),
        migrations.RenameField(
            model_name='financialprojectgov2023',
            old_name='plan_consider_currency',
            new_name='plan_consider_gov_currency',
        ),
        migrations.RenameField(
            model_name='financialprojectgov2023',
            old_name='plan_work',
            new_name='plan_work_gov',
        ),
        migrations.RenameField(
            model_name='financialprojectgov2023',
            old_name='plan_work_currency',
            new_name='plan_work_gov_currency',
        ),
    ]
