# Generated by Django 3.2.20 on 2023-08-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20230824_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
