# Generated by Django 3.2.20 on 2023-08-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_financialproject2023_number_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialproject2023',
            name='fact_stage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialproject2023',
            name='plan_stage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
